
/**************************************************************
 *	
 *	bundleofjoy, 8 bit, 11025Hz,
 *	1 channel, 517437 bytes/channel
 *	Total Size: 1 * 517437 + 4 (header) = 517481 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/fmoreno99/CS2261/FinalProject/bundleofjoy.wav
 *	Time-stamp: Thu Nov 21 14:03:04 2019
 *	
 **************************************************************/

#ifndef __BUNDLEOFJOYH__
#define __BUNDLEOFJOYH__

#define BUNDLEOFJOYFREQ 11025
#define BUNDLEOFJOYLEN 517437

extern const unsigned char bundleofjoy[517437];

#endif /* __BUNDLEOFJOYH__ */
