
/**************************************************************
 *	
 *	chasingSadness, 8 bit, 11025Hz,
 *	1 channel, 1166688 bytes/channel
 *	Total Size: 1 * 1166688 + 4 (header) = 1166732 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/fmoreno99/CS2261/FinalProject/chasingSadness.wav
 *	Time-stamp: Sun Nov 24 20:25:40 2019
 *	
 **************************************************************/

#ifndef __CHASINGSADNESSH__
#define __CHASINGSADNESSH__

#define CHASINGSADNESSFREQ 11025
#define CHASINGSADNESSLEN 1166688

extern const unsigned char chasingSadness[1166688];

#endif /* __CHASINGSADNESSH__ */
