
/**************************************************************
 *	
 *	morethanafeeling, 8 bit, 11025Hz,
 *	1 channel, 368965 bytes/channel
 *	Total Size: 1 * 368965 + 4 (header) = 369009 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/fmoreno99/CS2261/FinalProject/morethanafeeling.wav
 *	Time-stamp: Thu Nov 21 23:49:25 2019
 *	
 **************************************************************/

#ifndef __MORETHANAFEELINGH__
#define __MORETHANAFEELINGH__

#define MORETHANAFEELINGFREQ 11025
#define MORETHANAFEELINGLEN 368965

extern const unsigned char morethanafeeling[368965];

#endif /* __MORETHANAFEELINGH__ */
