
/**************************************************************
 *	
 *	sadnessCrying, 8 bit, 11025Hz,
 *	1 channel, 71579 bytes/channel
 *	Total Size: 1 * 71579 + 4 (header) = 71623 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/fmoreno99/CS2261/FinalProject/sadnessCrying.wav
 *	Time-stamp: Thu Nov 21 15:09:30 2019
 *	
 **************************************************************/

#ifndef __SADNESSCRYINGH__
#define __SADNESSCRYINGH__

#define SADNESSCRYINGFREQ 11025
#define SADNESSCRYINGLEN 71579

extern const unsigned char sadnessCrying[71579];

#endif /* __SADNESSCRYINGH__ */
