
/**************************************************************
 *	
 *	shoot, 8 bit, 11025Hz,
 *	1 channel, 3328 bytes/channel
 *	Total Size: 1 * 3328 + 4 (header) = 3372 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/fmoreno99/CS2261/FinalProject/shoot.wav
 *	Time-stamp: Sun Nov 24 19:37:42 2019
 *	
 **************************************************************/

#ifndef __SHOOTH__
#define __SHOOTH__

#define SHOOTFREQ 11025
#define SHOOTLEN 3328

extern const unsigned char shoot[3328];

#endif /* __SHOOTH__ */
